### ISSUE TITLE
Pressure Converter crash

### ISSUE THREAD

**Issue by lorddagan** [Tekkify/Tekkify#7] opened 2015-01-05 19:52 UTC
Noticed a constant crash issue when trying to use the FSP Pressure Converter.

 This item is designed to change FSP steam into a steam usable by railcraft and TE. The wiki's and vids all show it should work with the following setup:

 Steam tank->FSP Pipe->Converter->Fluid Conduit->Dynamo

 Whenever I start the setup, it causes me to crash to desktop, presumable once the animation starts.

 Crash log posted here

http://pastebin.com/LHD21uhH

 Dagan

**Comment by Haidyn** [comment] 2015-01-05 21:02
Looks like an EnderIO issue, we'll get it reported to CrazyPants.

Fluid Extraction Tubes work in the meantime.
http://i.haidyn.me/328H08W.jpg

**Comment by lorddagan** [comment] 2015-01-05 21:08
never used the tubes mod before, wasn't sure of that pipe. Will give it a go in my next attempt. Thank you.

**Comment by Nentify** [comment] 2015-01-05 21:49
Closing, will report to the EnderIO issue tracker.

**Closed by Nentify** 2015-01-05 21:49 UTC

**Comment by satanicsanta** [comment] 2015-01-07 01:13
This is a known Flaxbeard's Steam Power issue. I do know the cause just not the fix. I'll push an update as soon as I or Xbony get it fixed.
